### PR TITLE
feature(settings): add settings management

### PR DESCRIPTION
**Pull request by SkyzohKey**

### CODE REVIEW

**Comment by benwaffle** [comment]
you should be using GSettings

**Comment by SkyzohKey** [comment]
GSettings format is shit :x
Libconfig is lightweight and simple to use, and i'm not sure that GSettings would work on Windows...

**Comment by benwaffle** [comment]
What's wrong with the GSettings format? and it does work on windows

**Comment by SkyzohKey** [comment]
The XML format is shit :x

**Comment by benwaffle** [comment]
It's not stored in XML, you only specify your schema in XML. And you haven't said what's shit about it

**Comment by SkyzohKey** [comment]
> It's not stored in XML, you only specify your schema in XML.

Ah ? o.ô

**Pull request merged**
