### PR TITLE
chore(appimage): auto-build appimage with travis builds

### PR DESCRIPTION
**Pull request by SkyzohKey**
Thanks to @probonopd we now have `appimage` packages auto generated for every travis build!

### CODE REVIEW

**Comment by probonopd** [comment]
Please don't merge just yet. I discovered there is a lot of stuff in the AppImage which shouldn't go there, need to fix the script first.

**Comment by probonopd** [comment]
I updated the script, should be OK now. More testing on different distros is required though.

**Comment by GranPC** [comment]
Doesn't work on elementary OS 0.3.2 (based on Ubuntu 14.04).

```
granpc@mero-freya:~/Downloads$ ./ricin-gitb713cce-glibc-x86-64.appimage 
/tmp/.mount_94O07C/usr/bin/ricin.wrapper
zenity, kdialog, Xdialog missing. Skipping ./bin//ricin.wrapper.
/tmp/.mount_94O07C/usr/bin/ricin: symbol lookup error: ./lib/libgtk-3.so.0: undefined symbol: g_list_model_get_type
```

**Comment by SkyzohKey** [comment]
@probonopd ping
It seems that the packaged gtk+3 version is 3.16 while Ricin requires >= 3.18 :x

**Comment by SkyzohKey** [comment]
Well, just tested this on Ubuntu, Fedora, Debian, OpenSuse and ArchLinux and it worked on every one. ricin-0.1.1.appimage is also now downloadable at https://ricin.im. Thus merging!

@probonopd Thanks again for this awesome job ;)

**Comment by probonopd** [comment]
Opened https://github.com/RicinApp/Ricin/issues/127

**Pull request merged**
